name: Itch.io release

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Remove unwanted files
        run: |
          rm -rf Other
          rm -rf img
          rm -rf .github
      - name: Prepare Linux upload
        run: |
          mv game/windows ..
          mv launcher-win32-ia32 ..
          mv launch_game.bat ..
      - name: Upload Linux build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: ground-mosh
          ITCH_USER: turupawn
          PACKAGE: .
      - name: Prepare Windows upload
        run: |
          mv ../windows ./game
          mv ../launcher-win32-ia32 .
          mv ../launch_game.bat .
          mv game/linux ..
          mv launcher-linux-x64 ..
          mv launch_game.sh ..
      - name: Upload Windows build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: ground-mosh
          ITCH_USER: turupawn
          PACKAGE: .
